# MySQL profile settings, reads configuration from environment variables
database=mysql

# SQL init scripts location
spring.sql.init.schema-locations=classpath*:db/${database}/schema.sql
spring.sql.init.data-locations=classpath*:db/${database}/data.sql

# --- Database Connection Settings (to be provided by the environment) ---
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Specify the MySQL driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA settings for production
# 'validate' checks if the schema matches the code, but does not make changes.
spring.jpa.hibernate.ddl-auto=validate